### PR TITLE
Vivek feature1

### PR DESCRIPTION
**Pull request by vivekshah1801**
This is new pull request

### CODE REVIEW

**Comment by avni0405** [comment]
mane phone shu kam karyo

**Review by nidzshah2702 — COMMENTED** [review]
ej toh phone kem karyo
janta wants to know

**Comment by vivekshah1801** [comment]
Tel leva jav badha
#YehjahanHuaBegana

**Review by nidzshah2702 — CHANGES_REQUESTED** [review]
need changes

**Review by avni0405 — DISMISSED** [review]
approve request

**Comment by vivekshah1801** [comment]
Done changes.

**Pull request merged**
